# Generated by Django 4.2.6 on 2025-02-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='name',
            new_name='name_of_certificate',
        ),
        migrations.AddField(
            model_name='certificate',
            name='name_of_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
