# Generated by Django 4.2.6 on 2025-02-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_rename_name_certificate_name_of_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='name_of_certificate',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name_of_user',
        ),
    ]
