# Generated by Django 4.2.6 on 2025-02-20 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_certificate'),
        ('certificate', '0003_rename_name_of_certificate_certificate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='portfolio.userdetails'),
        ),
    ]
