# Generated by Django 4.2.6 on 2025-02-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_alter_certificate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='additionol_testseries_attempted',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='started_at',
        ),
    ]
