# Generated by Django 4.2.6 on 2025-02-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_userdetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
