# Generated by Django 4.2.6 on 2025-03-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_userdetails_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
