# Generated by Django 4.2.6 on 2025-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
