# Generated by Django 4.2.6 on 2025-02-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_email',
        ),
    ]
