# Generated by Django 4.2.6 on 2025-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsregistered',
            name='interviw_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
