# Generated by Django 5.1.4 on 2024-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialmodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_image'),
        ),
    ]
